const mongoose = require("mongoose");

const languageSchema = mongoose.Schema({
  lang: {
    type: String,
    required: true,
  },
  Name: {
    type: String,
    required: true,
    trem: true,
    maxlength: 50,
    minlength: 3,
  },
  sub: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  address: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  email: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  phone: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 10,
    minlength: 10,
  },

  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  titleeq1: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  titleeq2: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  titleeq3: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  titleeq4: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  boadr1: {
    type: String,
    required: true,
    trim: true,
    maxlength: 90,
    minlength: 3,
  },
  boadr2: {
    type: String,
    required: true,
    trim: true,
    maxlength: 90,
    minlength: 3,
  },
  boadr3: {
    type: String,
    required: true,
    trim: true,
    maxlength: 90,
    minlength: 3,
  },
  boadr4: {
    type: String,
    required: true,
    trim: true,
    maxlength: 90,
    minlength: 3,
  },
  year1: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 4,
    minlength: 4,
  },
  year2: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 4,
    minlength: 4,
  },
  year3: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 4,
    minlength: 4,
  },
  year4: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 4,
    minlength: 4,
  },
  institution1: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  institution2: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  institution3: {
    type: String,
    required: true,
    trim: true,
    maxlength: 50,
    minlength: 3,
  },
  institution4: {
    type: String,
    required: true,
    trim: true,
    maxlength: 90,
    minlength: 3,
  },
  percentage1: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 3,
    minlength: 2,
  },
  percentage2: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 3,
    minlength: 2,
  },
  percentage3: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 3,
    minlength: 2,
  },
  percentage4: {
    type: Number,
    required: true,
    trim: true,
    maxlength: 3,
    minlength: 2,
  },
  created_at: {
    type: Date,
    required: true,
    default: Date.now,
  },
});

const Language = mongoose.model("Education", languageSchema);
module.exports = Language;
